### PR TITLE
Refactor logos and add Wherobots info

### PR DESCRIPTION
**Pull request by jiayuasu**
## Changes

1. Replace the giant logo image with a number of individual logos so anyone can easily add their own logo in the future.
2. Add Apache Sedona logo, Wherobots logo and Wherobots GeoParquet introduction

### Wide

image

### Narrow

image

### CODE REVIEW

**Comment by jiayuasu** [comment]
@cholmes Hi Chris, would you please review this PR?

**Comment by jatorre** [comment]
Thanks. The order we used on the slide was, first libraries and companies that are contiributing to the effort, and the datawarehouses that have expressed interest in adding support for it. And then alphabetically, so Sedona should go after Planet, and wherobots after voltron.

And I see GDAL misplaced, I guess for lack of space, but should go after foursquare.

We might have to think this further considering other products have added support too and have participated on the sessions.

**Comment by jiayuasu** [comment]
@jatorre Thanks. I thought the original logos were sorted alphabetically. I have fixed the order of the logos according to the old image and added Apache Sedona and Wherobots. Please review.

**Comment by jiayuasu** [comment]
@jatorre @cholmes Could you please merge this PR if you have no other comments?

**Review by jatorre — COMMENTED** [review]
All good with me

**Comment by cholmes** [comment]
Apologies for the slow response - it's been busy. Merging it in now.

**Pull request merged**
